package com.spring.trip_booking.enums;

public enum ActivityType {
	RATING, FLIGHT_BOOKING, HOTEL_BOOKING, SIGN_UP,HOTEL_REQUEST,FLIGHT_REQUEST,VENDOR_REQUEST,LOGIN,LOGOUT,DELETE_USER,DELETE_HOTEL,DELETE_FLIGHT, DELETE_FLIGHT_REQUEST, DELETE_HOTEL_REQUEST, DELETE_VENDOR_REQUEST, APPROVE_FLIGHT_REQUEST, APPROVE_HOTEL_REQUEST, APPROVE_VENDOR_REQUEST 
}
